### ISSUE TITLE
PyTorch 2.0 support

### ISSUE THREAD

**Issue by sef43** [openmm/openmm-torch#100]
Following from https://github.com/openmm/NNPOps/issues/92 making a thread to discuss general PyTorch 2.0 support.

Pytorch 2.0 release: https://github.com/pytorch/pytorch/releases/tag/v2.0.0

Important points:

Pytorch 2.0 has introduced the [`compile` feature](https://pytorch.org/get-started/pytorch-2.0/#pytorch-2x-faster-more-pythonic-and-as-dynamic-as-ever), this seems to produce faster code than jit.script and jit.trace.

- [ ] However, can something that has been `torch.compile`'d be loaded into c++ so we can use it with `torchForce`? 

It seems PyTorch are moving away from the c++ api "a feature that pushes PyTorch performance to new heights and starts the move for parts of PyTorch from C++ back into Python." This might become a problem for the way openmm-torch works

- [x] To release on conda-forge we will need to wait for the conda-forge pytorch build to be updated to 2.0, here is the issue from the feedstock: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/151

**Comment by peastman** [comment]
> force = torch.compile(TorchForce('mymodel.pt'))

I think all that would do is compile the tiny amount of wrapper code around the C++ class?  It wouldn't know how to compile anything inside the C++ code.

**Comment by RaulPPelaez** [comment]
The problems I see in the feedstock are due to not compatible versions being installed. Pytorch2 seems to require CUDA >=11.2, but the builds try to install 11.0, 11.1...

**Comment by RaulPPelaez** [comment]
BTW @sef43, can you comment on the segfaults? Is this something that happens also with other pytorch versions? I dont think I have not encountered this.

**Comment by sef43** [comment]
building using these steps:
```
conda create -n build_pt20
mamba install -c conda-forge python=3.10 openmmtools openmm cudatoolkit=11.7 pytorch=2.0 pytest swig
```
```
git clone https://github.com/openmm/openmm-torch.git
cd openmm-torch
mkdir build
cd build
export Torch_DIR="$(python -c 'import torch.utils; print(torch.utils.cmake_prefix_path)')"
cmake .. -DOPENMM_DIR=$CONDA_PREFIX       -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make install
make PythonInstall
export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib/python3.10/site-packages/torch/lib:${LD_LIBRARY_PATH}"
```
Then the following test script has a segfault:
```python
import torch
from openmmtorch import TorchForce
import sys
from openmm import System
import numpy as np

# Create a random cloud of particles.
numParticles = 10
system = System()
positions = np.random.rand(numParticles, 3)
for _ in range(numParticles):
    system.addParticle(1.0)

#Simple Harmonic force from openmm-torch README
class ForceModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, positions):
        return torch.sum(positions**2)

module = torch.jit.script(ForceModule())
module.save('harmonic.pt')
force = TorchForce('harmonic.pt')
system.addForce(force)
```
gdb backtrace:


<details>

```
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
(gdb) run mytest.py 
Starting program: /home/sfarr/miniconda3/envs/build_pt20/bin/python mytest.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fff5dc54640 (LWP 3924808)]
[New Thread 0x7fff5d453640 (LWP 3924809)]
[New Thread 0x7fff54c52640 (LWP 3924810)]
[New Thread 0x7fff4c451640 (LWP 3924811)]
[New Thread 0x7fff43c50640 (LWP 3924812)]
[New Thread 0x7fff3b44f640 (LWP 3924813)]
[New Thread 0x7fff32c4e640 (LWP 3924814)]
[New Thread 0x7fff2a44d640 (LWP 3924815)]
[New Thread 0x7fff21c4c640 (LWP 3924816)]
[New Thread 0x7fff1944b640 (LWP 3924817)]
[New Thread 0x7fff08c4a640 (LWP 3924818)]
[New Thread 0x7fff08449640 (LWP 3924819)]
[New Thread 0x7ffeffc48640 (LWP 3924820)]
[New Thread 0x7ffef7447640 (LWP 3924821)]
[New Thread 0x7ffeeec46640 (LWP 3924822)]
[New Thread 0x7ffede445640 (LWP 3924823)]
[New Thread 0x7ffed5c44640 (LWP 3924824)]
[New Thread 0x7ffecd443640 (LWP 3924825)]
[New Thread 0x7ffec4c42640 (LWP 3924826)]
[New Thread 0x7ffec4441640 (LWP 3924827)]
[New Thread 0x7ffeb3c40640 (LWP 3924828)]
[New Thread 0x7ffeab43f640 (LWP 3924829)]
[New Thread 0x7ffeaac3e640 (LWP 3924830)]
[New Thread 0x7ffe9a43d640 (LWP 3924831)]
[New Thread 0x7ffe91c3c640 (LWP 3924832)]
[New Thread 0x7ffe9143b640 (LWP 3924833)]
[New Thread 0x7ffe80c3a640 (LWP 3924834)]
[New Thread 0x7ffe78439640 (LWP 3924835)]
[New Thread 0x7ffe77c38640 (LWP 3924836)]
[New Thread 0x7ffe67437640 (LWP 3924837)]
[New Thread 0x7ffe5ec36640 (LWP 3924838)]
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
PyObject_IsInstance (inst=0x7ffff6d25bf0, cls=0x0) at /usr/local/src/conda/python-3.10.10/Objects/abstract.c:2698
2698	/usr/local/src/conda/python-3.10.10/Objects/abstract.c: No such file or directory.
(gdb) bt
#0  PyObject_IsInstance (inst=0x7ffff6d25bf0, cls=0x0) at /usr/local/src/conda/python-3.10.10/Objects/abstract.c:2698
#1  0x00007ffe506b9566 in torch::jit::as_module(pybind11::handle) ()
   from /home/sfarr/miniconda3/envs/build_pt20/lib/python3.10/site-packages/_openmmtorch.cpython-310-x86_64-linux-gnu.so
#2  0x00007ffe506aa657 in _wrap_new_TorchForce ()
   from /home/sfarr/miniconda3/envs/build_pt20/lib/python3.10/site-packages/_openmmtorch.cpython-310-x86_64-linux-gnu.so
#3  0x00005555556946e0 in cfunction_call (func=0x7ffe4de2d490, args=<optimised out>, kwargs=<optimised out>)
    at /usr/local/src/conda/python-3.10.10/Objects/methodobject.c:552
#4  0x00005555556a1209 in _PyObject_Call (kwargs=<optimised out>, args=0x7ffff6d2e3b0, callable=0x7ffe4de2d490, tstate=0x555555910e70)
    at /usr/local/src/conda/python-3.10.10/Objects/call.c:305
#5  PyObject_Call (callable=0x7ffe4de2d490, args=0x7ffff6d2e3b0, kwargs=<optimised out>) at /usr/local/src/conda/python-3.10.10/Objects/call.c:317
#6  0x000055555568a39b in do_call_core (kwdict=0x0, callargs=0x7ffff6d2e3b0, func=0x7ffe4de2d490, trace_info=0x7fffffffd8b0, tstate=<optimised out>)
    at /usr/local/src/conda/python-3.10.10/Python/ceval.c:5915
#7  _PyEval_EvalFrameDefault (tstate=<optimised out>, f=0x7ffe45652f80, throwflag=<optimised out>) at /usr/local/src/conda/python-3.10.10/Python/ceval.c:4277
#8  0x000055555568d001 in _PyEval_EvalFrame (throwflag=0, f=0x7ffe45652f80, tstate=0x555555910e70)
    at /usr/local/src/conda/python-3.10.10/Include/internal/pycore_ceval.h:46
#9  _PyEval_Vector (kwnames=0x0, argcount=<optimised out>, args=<optimised out>, locals=0x0, con=0x7ffe4d317bf0, tstate=0x555555910e70)
    at /usr/local/src/conda/python-3.10.10/Python/ceval.c:5065
#10 _PyFunction_Vectorcall (kwnames=0x0, nargsf=<optimised out>, stack=<optimised out>, func=0x7ffe4d317be0) at /usr/local/src/conda/python-3.10.10/Objects/call.c:342
#11 _PyObject_FastCallDictTstate (tstate=0x555555910e70, callable=0x7ffe4d317be0, args=<optimised out>, nargsf=<optimised out>, kwargs=<optimised out>)
    at /usr/local/src/conda/python-3.10.10/Objects/call.c:142
#12 0x000055555569e0fb in _PyObject_Call_Prepend (kwargs=0x0, args=0x7ffff6d2e260, obj=<optimised out>, callable=0x7ffe4d317be0, tstate=0x555555910e70)
    at /usr/local/src/conda/python-3.10.10/Objects/call.c:431
#13 slot_tp_init (self=<optimised out>, args=<optimised out>, kwds=<optimised out>) at /usr/local/src/conda/python-3.10.10/Objects/typeobject.c:7734
#14 0x000055555568dd2b in type_call (kwds=0x0, args=0x7ffff6d2e260, type=<optimised out>) at /usr/local/src/conda/python-3.10.10/Objects/typeobject.c:1135
#15 _PyObject_MakeTpCall (tstate=0x555555910e70, callable=0x55555af72ff0, args=<optimised out>, nargs=<optimised out>, keywords=0x0)
    at /usr/local/src/conda/python-3.10.10/Objects/call.c:215
#16 0x00005555556894e1 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimised out>, args=0x7ffff6dc5ba8, callable=<optimised out>, tstate=<optimised out>)
    at /usr/local/src/conda/python-3.10.10/Include/cpython/abstract.h:112
#17 _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimised out>, args=0x7ffff6dc5ba8, callable=<optimised out>, tstate=<optimised out>)
    at /usr/local/src/conda/python-3.10.10/Include/cpython/abstract.h:99
#18 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimised out>, args=0x7ffff6dc5ba8, callable=<optimised out>)
    at /usr/local/src/conda/python-3.10.10/Include/cpython/abstract.h:123
#19 call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>, trace_info=0x7fffffffdba0, tstate=<optimised out>)
    at /usr/local/src/conda/python-3.10.10/Python/ceval.c:5891
#20 _PyEval_EvalFrameDefault (tstate=<optimised out>, f=0x7ffff6dc5a40, throwflag=<optimised out>) at /usr/local/src/conda/python-3.10.10/Python/ceval.c:4213
#21 0x000055555572f6a2 in _PyEval_EvalFrame (throwflag=0, f=0x7ffff6dc5a40, tstate=0x555555910e70)
    at /usr/local/src/conda/python-3.10.10/Include/internal/pycore_ceval.h:46
#22 _PyEval_Vector (tstate=0x555555910e70, con=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=<optimised out>)
    at /usr/local/src/conda/python-3.10.10/Python/ceval.c:5065
#23 0x000055555572f5e7 in PyEval_EvalCode (co=co@entry=0x7ffff6d16e40, globals=globals@entry=0x7ffff6cd8ec0, locals=locals@entry=0x7ffff6cd8ec0)
    at /usr/local/src/conda/python-3.10.10/Python/ceval.c:1134
#24 0x00005555557623fc in run_eval_code_obj (tstate=0x555555910e70, co=0x7ffff6d16e40, globals=0x7ffff6cd8ec0, locals=0x7ffff6cd8ec0)
    at /usr/local/src/conda/python-3.10.10/Python/pythonrun.c:1291
#25 0x000055555575d2d4 in run_mod (mod=<optimised out>, filename=<optimised out>, globals=0x7ffff6cd8ec0, locals=0x7ffff6cd8ec0, flags=<optimised out>, 
    arena=<optimised out>) at /usr/local/src/conda/python-3.10.10/Python/pythonrun.c:1312
#26 0x00005555555eb58d in pyrun_file (fp=0x5555559198b0, filename=0x7ffff6d22820, start=<optimised out>, globals=0x7ffff6cd8ec0, locals=0x7ffff6cd8ec0, closeit=1, 
    flags=0x7fffffffde98) at /usr/local/src/conda/python-3.10.10/Python/pythonrun.c:1208
#27 0x00005555557574f5 in _PyRun_SimpleFileObject (fp=0x5555559198b0, filename=0x7ffff6d22820, closeit=1, flags=0x7fffffffde98)
    at /usr/local/src/conda/python-3.10.10/Python/pythonrun.c:456
#28 0x00005555557570a3 in _PyRun_AnyFileObject (fp=0x5555559198b0, filename=0x7ffff6d22820, closeit=1, flags=0x7fffffffde98)
    at /usr/local/src/conda/python-3.10.10/Python/pythonrun.c:90
#29 0x0000555555754279 in pymain_run_file_obj (skip_source_first_line=0, filename=0x7ffff6d22820, program_name=0x7ffff6cdc490)
    at /usr/local/src/conda/python-3.10.10/Modules/main.c:357
#30 pymain_run_file (config=0x5555558f52a0) at /usr/local/src/conda/python-3.10.10/Modules/main.c:376
```

</details>

**Comment by sef43** [comment]
I was thinking of these segfaults: https://github.com/openmm/openmm-torch/issues/88, but I think they are different actually

**Comment by RaulPPelaez** [comment]
I opened #106 to work on this.

**Comment by RitaQian-westlake** [comment]
Hello,

I wonder if openmm-torch can support PyTorch 2.0 now? I found your most recent revision on this issue seemed to be in May, yet the conda package cannot support PyTorch 2.0 today. Is there any other form available like source code, or it has not been released so previous versions of PyTorch are still suggested?

**Comment by RaulPPelaez** [comment]
Thanks for the reminder, we were trying to get to the bottom of some issue in a test, see #106. Hopefully we can get a new conda-forge release soon.

**Comment by RaulPPelaez** [comment]
@RitaQian-westlake You should have torch2 compatibility in the latest release. #113

**Comment by RitaQian-westlake** [comment]
Great news! I'll try it. Thanks for your contribution.

**Comment by raimis** [comment]
OpenMM-Torch 1.1 with PyTorch 2 support has been released (https://github.com/openmm/openmm-torch/releases/tag/v1.1).
