### ISSUE TITLE
Error with installing openmmtorch and torch_scatter/torch_geometric

### ISSUE THREAD

**Issue by AdeeshKolluru** [openmm/openmm-torch#162]
I want to install `openmm-torch` and `pyg`. I'm wondering if there are any known versions of these packages that work together. 

Simple test 

```
conda create -n test python=3.12
conda activate test
conda install openmm-torch -c conda-forge
```

this installs `torch2.5.1.post303` with cuda version `11.8` on my system.

now when I try to install other packages through pip (conda isn't able to find a matching version)
```
pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.5.1+cu118.html
```
its unable to install these packages correctly

```
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "*/lib/python3.12/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "*/lib/python3.12/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "*/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: */lib/python3.12/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSsb
```

It does seem like TorchMDNet uses all these packages but by default their `environment.yml` doesn't install `openmm-torch`. It would be great to know if there's any way around this.

Thanks!

**Comment by peastman** [comment]
Mixing packages from pip and conda doesn't usually work.  They use different versions of the C++ ABI, so they can't link to each other.

I'm trying to create a pip package for OpenMM-Torch, but I'm currently blocked by a PyTorch bug.

**Comment by kleinhenz** [comment]
@peastman A wheel build would be great to have. Have you been able to make any progress? I'm curious what the torch bug is.

**Comment by peastman** [comment]
I figured out how to build Mac wheels, and I think I can do Linux ones for CPU and CUDA.  I'm stuck on Windows.  And I can't even install the SDK to build HIP wheels.  There isn't enough disk space on the runner.
