### ISSUE TITLE
Error on Reference platform when ForceModule has submodules 

### ISSUE THREAD

**Issue by xqding** [openmm/openmm-torch#41]
The following script works on both CUDA and OpenCL platforms, but fails on the Reference platform. It seems to happen when the ForceModule has submodules as in the script.

``` Python
import torch
import os
from openmmtorch import TorchForce
import simtk.openmm as omm
import simtk.unit as unit
import numpy as np

class ForceModule(torch.nn.Module):
    def __init__(self, num_particles):
        super(ForceModule, self).__init__()
	self.fc = torch.nn.Linear(num_particles*3, 1)

    def forward(self, positions):
        output = self.fc(torch.reshape(positions, [-1]))
        return output

# Render the compute graph to a TorchScript module
num_particles = 10
force_module = ForceModule(num_particles)
scripted_module = torch.jit.script(force_module)

positions = torch.randn(num_particles, 3)
output = force_module(positions)
print("output from force_module: output", output)

output = scripted_module(positions)
print("output from scripted_module: output", output)

# Serialize the compute graph to a file
os.makedirs("./output/test", exist_ok = True)
scripted_module.save('./output/test/model.pt')

torch_force = TorchForce('./output/test/model.pt')

# Add the TorchForce to your System
system = omm.System()
for i in range(num_particles):
    system.addParticle(1.0)
system.addForce(torch_force)

T = 300*unit.kelvin
fricCoef = 1./unit.picoseconds
stepsize = 2. * unit.femtoseconds

CUDA_platform = omm.Platform.getPlatformByName('CUDA')
CUDA_integrator = omm.LangevinMiddleIntegrator(T, fricCoef, stepsize)
context = omm.Context(system, CUDA_integrator, CUDA_platform)
context.setPositions(positions.numpy())
state = context.getState(getEnergy = True)
potential_energy = state.getPotentialEnergy()
print("potential energy from CUDA platform:", potential_energy)

OpenCL_platform = omm.Platform.getPlatformByName('OpenCL')
OpenCL_integrator = omm.LangevinMiddleIntegrator(T, fricCoef, stepsize)
context = omm.Context(system, OpenCL_integrator, OpenCL_platform)
context.setPositions(positions.numpy())
state = context.getState(getEnergy = True)
potential_energy = state.getPotentialEnergy()
print("potential energy from OpenCL platform:", potential_energy)

reference_platform = omm.Platform.getPlatformByName('Reference')
reference_integrator = omm.LangevinMiddleIntegrator(T, fricCoef, stepsize)
context = omm.Context(system, reference_integrator, reference_platform)
context.setPositions(positions.numpy())
state = context.getState(getEnergy = True)
potential_energy = state.getPotentialEnergy()
print("potential energy from reference platform:", potential_energy)
```
This is the output message:

```output from force_module: output tensor([0.0880], grad_fn=<AddBackward0>)
output from scripted_module: output tensor([0.0880], grad_fn=<AddBackward0>)
potential energy from CUDA platform: 0.08795830607414246 kJ/mol
potential energy from OpenCL platform: 0.08795826137065887 kJ/mol
Traceback (most recent call last):
  File "./script/single_protein_manybody/test.py", line 65, in <module>
    state = context.getState(getEnergy = True)
  File "/home/gridsan/dingxq/.conda/envs/openmm_torch/lib/python3.8/site-packages/simtk/openmm/openmm.py", line 13172, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
SystemError: <built-in function Context_getState> returned NULL without setting an error
Segmentation fault
```

**Comment by peastman** [comment]
Could you replace the call to `context.getState()` with `reference_integrator.step(1)` and see what the error message is?  There's a bug in 7.5.1 where if something inside `getState()` throws an exception, you get that uninformative error message instead of the correct one.  `step()` should throw the same exception, so we can see what the error actually is.

**Comment by xqding** [comment]
Thanks for the suggestion. Using `reference_integrator.step(1)` does provide more informative error message:

```
Traceback (most recent call last):
  File "./script/single_protein_manybody/test.py", line 67, in <module>
    reference_integrator.step(1)
  File "/home/gridsan/dingxq/.conda/envs/openmm_torch/lib/python3.8/site-packages/simtk/openmm/openmm.py", line 15515, in step
    return _openmm.LangevinMiddleIntegrator_step(self, steps)
simtk.openmm.OpenMMException: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 9, in forward
  def forward(self: __torch__.ForceModule,
    positions: Tensor) -> Tensor:
    output = (self.fc).forward(torch.reshape(positions, [-1]), )
              ~~~~~~~~~~~~~~~~ <--- HERE
    return output
  File "code/__torch__/torch/nn/modules/linear.py", line 13, in forward
    input: Tensor) -> Tensor:
    _0 = __torch__.torch.nn.functional.linear
    return _0(input, self.weight, self.bias, )
           ~~ <--- HERE
  File "code/__torch__/torch/nn/functional.py", line 4, in linear
    weight: Tensor,
    bias: Optional[Tensor]=None) -> Tensor:
  return torch.linear(input, weight, bias)
         ~~~~~~~~~~~~ <--- HERE

Traceback of TorchScript, original code (most recent call last):
  File "/home/gridsan/dingxq/.conda/envs/openmm_torch/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)
               ~~~~~~~~ <--- HERE
  File "/home/gridsan/dingxq/.conda/envs/openmm_torch/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    if has_torch_function_variadic(input, weight):
        return handle_torch_function(linear, (input, weight), input, weight, bias=bias)
    return torch._C._nn.linear(input, weight, bias)
           ~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: expected scalar type Double but found Float
```
The error is because of float precision. The reference platform uses double precision whereas the Pytorch module uses single precision by default. After I change the Pytorch module to double precision and both `context.getState()`  and `reference_integrator.step(1)` work on the Reference platform.

Thanks for the help!
